/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../anita-dajka-wedding-cms/schema.json
export type MasonryGallerySection = {
  _type: 'masonryGallerySection';
  title?: LocalizedString;
  description?: LocalizedText;
  items?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    _type: 'masonryImage';
    _key: string;
  }>;
};

export type ContactSection = {
  _type: 'contactSection';
  title?: LocalizedString;
  subtitle?: LocalizedString;
  redirectUrl?: string;
};

export type StorySection = {
  _type: 'storySection';
  items?: Array<{
    mainImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    secondMainImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    secondaryImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    title?: LocalizedString;
    description?: LocalizedText;
    layout?: 'right' | 'right-bottom' | 'left' | 'left-bottom';
    _type: 'storyRow';
    _key: string;
  }>;
};

export type GallerySection = {
  _type: 'gallerySection';
  title?: LocalizedString;
  subtitle?: LocalizedString;
  description?: LocalizedText;
  items?: Array<
    {
      _key: string;
    } & GalleryItem
  >;
};

export type GalleryItem = {
  _type: 'galleryItem';
  title?: LocalizedString;
  subtitle?: LocalizedString;
  link?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type PortfolioSection = {
  _type: 'portfolioSection';
  title?: LocalizedString;
  subtitle?: LocalizedString;
  description?: LocalizedText;
  items?: Array<
    {
      _key: string;
    } & PortfolioItem
  >;
};

export type PortfolioItem = {
  _type: 'portfolioItem';
  title?: LocalizedString;
  link?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  textAlignment?: 'left' | 'center' | 'right';
};

export type Testimonial = {
  _type: 'testimonial';
  author?: string;
  text?: LocalizedText;
};

export type AboutSection = {
  _type: 'aboutSection';
  title?: LocalizedString;
  prologue?: LocalizedString;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  secondaryImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  quote?: LocalizedString;
  description?: LocalizedBlockContent;
};

export type LocalizedBlockContent = {
  _type: 'localizedBlockContent';
  hu?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type NavLink = {
  _type: 'navLink';
  label?: LocalizedString;
  linkType?: 'internal' | 'external';
  internalLink?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
  externalUrl?: string;
  isExternal?: boolean;
  isHighlighted?: boolean;
};

export type Home = {
  _id: string;
  _type: 'home';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroSection?: HeroSection;
  highlightsSection?: HighlightsSection;
  videoSection?: VideoSection;
  introductionSection?: IntroductionSection;
  testimonialsSection?: TestimonialsSection;
};

export type TestimonialsSection = {
  _type: 'testimonialsSection';
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type IntroductionSection = {
  _type: 'introductionSection';
  title?: LocalizedString;
  subtitle?: LocalizedString;
  description?: LocalizedBlockContent;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocalizedString;
    _type: 'image';
  };
  ctaLabel?: LocalizedString;
  ctaUrl?: string;
};

export type VideoSection = {
  _type: 'videoSection';
  title?: LocalizedBlockContent;
  subtitle?: LocalizedString;
  description?: LocalizedBlockContent;
  video?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    media?: unknown;
    _type: 'file';
  };
  poster?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  posterAlt?: LocalizedString;
};

export type HighlightsSection = {
  _type: 'highlightsSection';
  title?: LocalizedString;
  subtitle?: LocalizedString;
  description?: LocalizedText;
  items?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    title?: LocalizedString;
    alt?: LocalizedString;
    description?: LocalizedText;
    _type: 'highlightImage';
    _key: string;
  }>;
};

export type HeroSection = {
  _type: 'heroSection';
  title?: LocalizedString;
  subtitle?: LocalizedString;
  items?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    title?: LocalizedString;
    subtitle?: LocalizedString;
    alt?: LocalizedString;
    _type: 'heroImage';
    _key: string;
  }>;
};

export type Footer = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: LocalizedString;
  tagline?: LocalizedString;
  instagramHandle?: string;
  instagramImages?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
};

export type Header = {
  _id: string;
  _type: 'header';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  logoAlt?: LocalizedString;
  leftNavigation?: Array<
    {
      _key: string;
    } & NavLink
  >;
  rightNavigation?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  email?: string;
  phone?: string;
  instagramUrl?: string;
  facebookUrl?: string;
};

export type Inquiry = {
  _id: string;
  _type: 'inquiry';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  referralSource?:
    | 'instagram'
    | 'google'
    | 'facebook'
    | 'pinterest'
    | 'friend'
    | 'vendor'
    | 'other';
  eventDate?: string;
  location?: string;
  message?: string;
  submittedAt?: string;
  status?: 'new' | 'replied' | 'booked' | 'archived';
  source?: string;
  confirmEmail?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  parent?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
  slug?: Slug;
  subtitle?: LocalizedString;
  description?: LocalizedText;
  icon?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & IntroductionSection)
    | ({
        _key: string;
      } & AboutSection)
    | ({
        _key: string;
      } & PortfolioSection)
    | ({
        _key: string;
      } & HighlightsSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & StorySection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & ContactSection)
    | ({
        _key: string;
      } & MasonryGallerySection)
  >;
  seo?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
};

export type LocalizedText = {
  _type: 'localizedText';
  hu?: string;
  en?: string;
};

export type LocalizedString = {
  _type: 'localizedString';
  hu?: string;
  en?: string;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | MasonryGallerySection
  | ContactSection
  | StorySection
  | GallerySection
  | GalleryItem
  | PortfolioSection
  | PortfolioItem
  | Testimonial
  | AboutSection
  | LocalizedBlockContent
  | NavLink
  | Home
  | TestimonialsSection
  | IntroductionSection
  | VideoSection
  | HighlightsSection
  | HeroSection
  | Footer
  | Header
  | Settings
  | Inquiry
  | Page
  | LocalizedText
  | LocalizedString
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;
